import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/ui/Navbar';
import Footer from '@/components/ui/Footer';
import Providers from '@/components/common/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-screen" suppressHydrationWarning>
        <Providers>
          <Navbar />
          <section className="pt-24 min-h-[80vh]">{children}</section>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
